# Generated by Django 5.2.17 on 2026-10-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='document_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='document_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
