# Generated by Django 5.2.18 on 2026-10-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_article_document_id_heroslide_document_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('badge', models.CharField(blank=True, max_length=120)),
                ('headline', models.CharField(max_length=220)),
                ('subheadline', models.TextField(blank=True)),
                ('android_label', models.CharField(blank=True, max_length=80)),
                ('ios_label', models.CharField(blank=True, max_length=80)),
                ('android_file', models.CharField(blank=True, max_length=400)),
                ('ios_file', models.CharField(blank=True, max_length=400)),
                ('android_store_url', models.CharField(blank=True, max_length=400)),
                ('ios_store_url', models.CharField(blank=True, max_length=400)),
                ('note', models.CharField(blank=True, max_length=260)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
